// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// pxls
arma::mat pxls(arma::mat im, arma::vec delta, arma::mat tilt, arma::vec x, arma::vec y);
RcppExport SEXP _zernike_pxls(SEXP imSEXP, SEXP deltaSEXP, SEXP tiltSEXP, SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type im(imSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type tilt(tiltSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(pxls(im, delta, tilt, x, y));
    return rcpp_result_gen;
END_RCPP
}
// readraw
NumericMatrix readraw(CharacterVector fname, NumericVector channels);
RcppExport SEXP _zernike_readraw(SEXP fnameSEXP, SEXP channelsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type fname(fnameSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type channels(channelsSEXP);
    rcpp_result_gen = Rcpp::wrap(readraw(fname, channels));
    return rcpp_result_gen;
END_RCPP
}
// rzernike
NumericVector rzernike(NumericVector rho, int n, int m);
RcppExport SEXP _zernike_rzernike(SEXP rhoSEXP, SEXP nSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(rzernike(rho, n, m));
    return rcpp_result_gen;
END_RCPP
}
// zpmC
NumericMatrix zpmC(NumericVector rho, NumericVector theta, int maxorder);
RcppExport SEXP _zernike_zpmC(SEXP rhoSEXP, SEXP thetaSEXP, SEXP maxorderSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< int >::type maxorder(maxorderSEXP);
    rcpp_result_gen = Rcpp::wrap(zpmC(rho, theta, maxorder));
    return rcpp_result_gen;
END_RCPP
}


RcppExport void id_dxy_uw(void *, void *, void *, void *, void *, void *, void *, void *);
RcppExport void id_uw(void *, void *, void *, void *);
RcppExport void q_uw(void *, void *, void *, void *, void *);
RcppExport void read_jpg_img(void *, void *, void *, void *, void *, void *, void *);
RcppExport void read_jpg_img_info(void *, void *, void *, void *, void *);
RcppExport void read_tiff_img(void *, void *, void *, void *, void *, void *, void *);
RcppExport void read_tiff_img_info(void *, void *, void *, void *, void *);
RcppExport void resize_image(void *, void *, void *, void *, void *, void *, void *);

static const R_CallMethodDef CallEntries[] = {
    {"_zernike_pxls", (DL_FUNC) &_zernike_pxls, 5},
    {"_zernike_readraw", (DL_FUNC) &_zernike_readraw, 2},
    {"_zernike_rzernike", (DL_FUNC) &_zernike_rzernike, 3},
    {"_zernike_zpmC", (DL_FUNC) &_zernike_zpmC, 3},
    {NULL, NULL, 0}
};

static const R_CMethodDef CMethods[] = {
    {"id_dxy_uw",          (DL_FUNC) &id_dxy_uw,          8},
    {"id_uw",              (DL_FUNC) &id_uw,              4},
    {"q_uw",               (DL_FUNC) &q_uw,               5},
    {"read_jpg_img",       (DL_FUNC) &read_jpg_img,       7},
    {"read_jpg_img_info",  (DL_FUNC) &read_jpg_img_info,  5},
    {"read_tiff_img",      (DL_FUNC) &read_tiff_img,      7},
    {"read_tiff_img_info", (DL_FUNC) &read_tiff_img_info, 5},
    {"resize_image",       (DL_FUNC) &resize_image,       7},
    {NULL, NULL, 0, NULL}
};


RcppExport void R_init_zernike(DllInfo *dll) {
    R_registerRoutines(dll, CMethods, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
