# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lspsiC <- function(images, phases, wt) {
    .Call(`_zernike_lspsiC`, images, phases, wt)
}

aiapsiC <- function(images, phases_init, ptol, maxiter, trace) {
    .Call(`_zernike_aiapsiC`, images, phases_init, ptol, maxiter, trace)
}

gpcapsiC <- function(images, ptol, maxiter, trace) {
    .Call(`_zernike_gpcapsiC`, images, ptol, maxiter, trace)
}

pxls <- function(im, delta, tilt, df, x, y, z3) {
    .Call(`_zernike_pxls`, im, delta, tilt, df, x, y, z3)
}

readraw <- function(fname, channels) {
    .Call(`_zernike_readraw`, fname, channels)
}

rzernike <- function(rho, n, m) {
    .Call(`_zernike_rzernike`, rho, n, m)
}

zpmC <- function(rho, theta, maxorder) {
    .Call(`_zernike_zpmC`, rho, theta, maxorder)
}

